// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hfgfazacqkykslxqtsom.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhmZ2ZhemFjcWt5a3NseHF0c29tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MDI2MzQsImV4cCI6MjA2MDk3ODYzNH0.zzAP_SlH2UDd7J0PiGmQ_hB9gr-Y8ToSHKUY5nAnibo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);